"""Added new table

Revision ID: 077d7953d900
Revises: 1d363b06451f
Create Date: 2025-01-10 18:30:00.852686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077d7953d900'
down_revision = '1d363b06451f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdes_price', sa.Float(), nullable=False),
    sa.Column('pdes_market_cap', sa.Float(), nullable=False),
    sa.Column('pdes_circulating_supply', sa.Float(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('pdes_supply_left', sa.Float(), nullable=False),
    sa.Column('pdes_total_supply', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('BTCAddress', sa.String(length=30), nullable=False),
    sa.Column('BTCAddressSeed', sa.String(length=50), nullable=False),
    sa.Column('ETHAddress', sa.String(length=30), nullable=False),
    sa.Column('ETHAddressSeed', sa.String(length=50), nullable=False),
    sa.Column('LTCAddress', sa.String(length=30), nullable=False),
    sa.Column('LTCAddressSeed', sa.String(length=50), nullable=False),
    sa.Column('USDCAddress', sa.String(length=30), nullable=False),
    sa.Column('USDCAddressSeed', sa.String(length=50), nullable=False),
    sa.Column('PDESAddres', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['PDESAddres'], ['user.username'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdes_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_referrer_id', 'user', ['referrer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_referrer_id', type_='foreignkey')

    op.drop_table('pdes_transaction')
    op.drop_table('notification')
    op.drop_table('account_detail')
    op.drop_table('utility')
    op.drop_table('coin_price_history')
    # ### end Alembic commands ###
