"""added transaction_completed to Transaction Table

Revision ID: 0a2c2a5718eb
Revises: c89f5ec5d8cf
Create Date: 2025-01-12 20:39:48.140383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2c2a5718eb'
down_revision = 'c89f5ec5d8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_completed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('fk_user_referrer_id', ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_referrer_id', type_='unique')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('transaction_completed')

    # ### end Alembic commands ###
