"""Change refferral_code to referral_code

Revision ID: 632748e93a42
Revises: 9f8ee3aafd8f
Create Date: 2024-12-30 13:31:41.355041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632748e93a42'
down_revision = '9f8ee3aafd8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=16), nullable=True))
        batch_op.create_unique_constraint('fk_user_referrer_id', ['referral_code'])
        batch_op.drop_column('refferral_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refferral_code', sa.VARCHAR(length=16), nullable=True))
        batch_op.drop_constraint('fk_user_referrer_id', type_='unique')
        batch_op.drop_column('referral_code')

    # ### end Alembic commands ###
