"""Add helper function to Balance table

Revision ID: 88832811ba01
Revises: e65f2dc0eee2
Create Date: 2025-01-14 14:25:47.535774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88832811ba01'
down_revision = 'e65f2dc0eee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rewards', sa.Float(), nullable=False, server_default="0.0"))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('rewards')

    # ### end Alembic commands ###
