"""adding currency and crypto_adress to Transaction table

Revision ID: 8be24f949e7b
Revises: d93879c3a52a
Create Date: 2025-01-18 19:57:47.057019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be24f949e7b'
down_revision = 'd93879c3a52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('crypto_address', sa.String(length=20), nullable=True))
        batch_op.drop_column('btc_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('btc_address', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('crypto_address')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
