"""added sticks and is_blocked column to User Table

Revision ID: 99ca9feb5ff1
Revises: 63965200158c
Create Date: 2025-01-21 10:15:38.373026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ca9feb5ff1'
down_revision = '63965200158c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sticks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('correct_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('correct_balance')
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('sticks')

    # ### end Alembic commands ###
