"""Add refresh_key field to User model

Revision ID: b103104dd000
Revises: 632748e93a42
Create Date: 2025-01-04 12:31:29.390474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b103104dd000'
down_revision = '632748e93a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_key', sa.String(length=128), nullable=True))
        batch_op.create_foreign_key('fk_user_referrer_id', 'user', ['referrer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_referrer_id', type_='foreignkey')
        batch_op.drop_column('refresh_key')

    # ### end Alembic commands ###
