"""Add daily percentage to RewardConfig

Revision ID: bd3ff7d4903b
Revises: 
Create Date: 2025-03-03 04:39:56.844887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd3ff7d4903b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_detail', schema=None) as batch_op:
        batch_op.alter_column('BTCAddress',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.alter_column('BTCAddressSeed',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('ETHAddress',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.alter_column('ETHAddressSeed',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('LTCAddress',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.alter_column('LTCAddressSeed',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('USDCAddress',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.alter_column('USDCAddressSeed',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('PDESAddress',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.drop_constraint('account_detail_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['PDESAddress'], ['username'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('reward_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage_daily', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.alter_column('percentage_weekly',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'),
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('reward_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('percentage_weekly',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('percentage_daily')

    with op.batch_alter_table('account_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('account_detail_ibfk_1', 'user', ['PDESAddress'], ['username'], ondelete='CASCADE')
        batch_op.alter_column('PDESAddress',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('USDCAddressSeed',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('USDCAddress',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('LTCAddressSeed',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('LTCAddress',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('ETHAddressSeed',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('ETHAddress',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('BTCAddressSeed',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('BTCAddress',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
