"""added btc_address to Transaction

Revision ID: c89f5ec5d8cf
Revises: f5c37cb379da
Create Date: 2025-01-11 08:39:59.292442

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c89f5ec5d8cf"
down_revision = "f5c37cb379da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("btc_address", sa.String(length=20), nullable=True)
        )
        batch_op.alter_column(
            "account_number", existing_type=sa.VARCHAR(length=20), nullable=True
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_user_referrer_id", "user", ["referrer_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_referrer_id", type_="foreignkey")

    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.alter_column(
            "account_number", existing_type=sa.VARCHAR(length=20), nullable=False
        )
        batch_op.drop_column("btc_address")

    # ### end Alembic commands ###
