"""edited some table about the crypto

Revision ID: cdcb2832c23c
Revises: 8be24f949e7b
Create Date: 2025-01-19 18:18:35.500118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcb2832c23c'
down_revision = '8be24f949e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdes_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_earned', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdes_transaction', schema=None) as batch_op:
        batch_op.drop_column('reward_earned')

    # ### end Alembic commands ###
