"""added confirm_by to the Transaction table

Revision ID: d93879c3a52a
Revises: 886c57b844e7
Create Date: 2025-01-18 01:59:23.934417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93879c3a52a'
down_revision = '886c57b844e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_confirm_by', 'user', ['confirm_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_confirm_by', type_='foreignkey')
        batch_op.drop_column('confirm_by')

    # ### end Alembic commands ###
