"""Add role to User table

Revision ID: e5f657236e08
Revises: 0a2c2a5718eb
Create Date: 2025-01-13 11:18:12.544829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f657236e08'
down_revision = '0a2c2a5718eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
        batch_op.create_foreign_key('fk_user_referrer', 'user', ['referrer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_referrer', type_='foreignkey')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
