"""added rewards to User and Balance

Revision ID: e65f2dc0eee2
Revises: e5f657236e08
Create Date: 2025-01-13 20:29:50.292341

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = "e65f2dc0eee2"
down_revision = "e5f657236e08"
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    if "reward_config" not in inspector.get_table_names():
        op.create_table(
            "reward_config",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("percentage_weekly", sa.Float(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
    if "reward_setting" not in inspector.get_table_names():
        op.create_table(
            "reward_setting",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("weekly_percentage", sa.Float(), nullable=False),
            sa.Column("start_date", sa.DateTime(), nullable=True),
            sa.Column("end_date", sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
    with op.batch_alter_table("balance", schema=None) as batch_op:
        if not inspector.get_columns("balance"):
            batch_op.add_column(
                sa.Column("rewards", sa.Float(), nullable=False, server_default="00.00")
            )
    with op.batch_alter_table("user", schema=None) as batch_op:
        columns = [col["name"] for col in inspector.get_columns("user")]
        if "last_reward_date" not in columns:
            batch_op.add_column(
                sa.Column("last_reward_date", sa.DateTime(), nullable=True)
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_reward_date")

    with op.batch_alter_table("balance", schema=None) as batch_op:
        batch_op.drop_column("rewards")

    op.drop_table("reward_setting")
    op.drop_table("reward_config")
    # ### end Alembic commands ###
