name: Deploy PEDEX Flask Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e
            cd /var/www/myapp/backend/ || exit 1
            git pull origin main
            
            # Install python3-venv if missing
            if ! dpkg -l | grep -qw python3-venv; then
              echo "python3-venv is missing. Install it manually on the server."
              exit 1
            fi

            # Install dependencies
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt

            # Restart backend service without sudo password prompt
            echo "${{ secrets.SSH_USER }} ALL=(ALL) NOPASSWD: /bin/systemctl restart backend" | sudo tee /etc/sudoers.d/restart-backend
            sudo systemctl restart backend
