name: Deploy React Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and build
        run: |
          cd frontend
          npm ci
          npm i --save-dev @types/react @types/react-dom
          npm run build

      - name: Deploy build files to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete frontend/dist/ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/var/www/myapp/frontend/dist

      - name: Restart PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/myapp/frontend
            npm ci --omit=dev  # Install only production dependencies
            pm2 delete my-react-app || true
            pm2 start "serve -s build -l 3000" --name my-react-app
            pm2 save

            # Restart frontend service without sudo password prompt
            # echo "${{ secrets.SSH_USER }} ALL=(ALL) NOPASSWD: /bin/systemctl restart frontend" | sudo tee /etc/sudoers.d/restart-frontend
            # sudo systemctl restart frontend
